name: Refresh jsDelivr Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  refresh_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Refresh jsDelivr Cache
        run: |
          urls=(
            "https://purge.jsdelivr.net/gh/krisstibex/sing-box-manager@main/Install.ps1"
            "https://purge.jsdelivr.net/gh/DustinWin/clash_singbox-tools@main/sing-box-release/sing-box-windows-amd64.exe"
            "https://purge.jsdelivr.net/gh/winsw/winsw@releases/latest/download/WinSW-x64.exe"
            "https://purge.jsdelivr.net/gh/krisstibex/sing-box-manager@main/sing-box-manager.ba"
            "https://purge.jsdelivr.net/gh/krisstibex/sing-box-manager@main/sing-box-service.xml"
          )

          for url in "${urls[@]}"; do
            curl -s -X GET "$url"
          done
